### ISSUE TITLE
Infineon TPM: Get Firmware Version Major,Minor,Build,Revision

### ISSUE THREAD

**Issue by jHetzer** [texhex/BiosSledgehammer#24]
Regarding the issue that Windows/ Windows WMI does not provide the full TPM Firmware Version at least for Infineon TPM chips. The following code can be used to fix this:
(BiosSledgehammer.ps1 / Function: Update-TPMFirmware / Line: 1581)

[regex]$regex = "(?'Name'Firmware\WVersion)\W(?'Version'[0-9|\.]+)\W(?'Info'.+)"
(& ".\IFXTPMUpdate_TPM12_v0443.com" "/info")[6] -match $regex | Out-Null
$tpmFirmwareVersion = $Matches.Version

Programm from HP "sp82133" (ftp://ftp.hp.com/pub/softpaq/sp82001-82500/sp82133.exe)

**Comment by texhex** [comment]
Thanks @jHetzer, but I think this is no longer an issue after HP [updated to 6.43](https://support.hp.com/us-en/document/c05381064/). 

New devices that get a TPM 2.0 to TPM 2.1 BTO downgrade have now the 6.43 firmware where only one version exists. The old "try flash" method should be fine for the few devices that still have the botched 6.41 FW installed.
