### ISSUE TITLE
Folder name "ISA75DT-1.0.1.39" should be updated

### ISSUE THREAD

**Issue by PhilippRC** [texhex/BiosSledgehammer#32]
The script is looking for the folder with the new version "ISA75DT-1.0.3.215".

**Comment by texhex** [comment]
Could you please explain this? The release ZIP contains ISA75DT-1.0.3.215.

**Comment by texhex** [comment]
Or did you mean inside the Code view tab here in GitHub? There are indeed some zombie files there, I will exterminate them right away.

**Comment by texhex** [comment]
Done: 07d9d87dcb41e55765822efeb1561971bb19dd0f

**Comment by PhilippRC** [comment]
Thanks for the prompt feedback.
Yes, indeed I downloaded the master branch directly and not the release zip file.
