### ISSUE TITLE
PTPMFWUpdate Return Code = 262

### ISSUE THREAD

**Issue by Joseahan** [texhex/BiosSledgehammer#44]
Hello!

Have another issue on some models during the TPM upgrade step, i get the PTPMFWUpdate Return Code = 262 error, the drives are using GPT so i don't get it why the log says it cannot find it.
[TPMConfig64.log](https://github.com/texhex/BiosSledgehammer/files/1824234/TPMConfig64.log)

Any idea what it could be?
During OSD we create the regular OS partition, we get the BDE Partition and use a custom Recovry partition. Also i'm running the tool after the OS has been installed so its not running in WinPE

**Comment by texhex** [comment]
@Joseahan So the issue is closed, what was the reason because I never saw that error before?
