### ISSUE TITLE
HP EliteBook Folio 9470m

### ISSUE THREAD

**Issue by napzero** [texhex/BiosSledgehammer#46]
I tested on our own laptops.

[BIOS-Settings.txt](https://github.com/texhex/BiosSledgehammer/files/1834532/BIOS-Settings.txt)
[BIOS-Update.txt](https://github.com/texhex/BiosSledgehammer/files/1834533/BIOS-Update.txt)
[ME-Update.txt](https://github.com/texhex/BiosSledgehammer/files/1834535/ME-Update.txt)
[folders.zip](https://github.com/texhex/BiosSledgehammer/files/1834563/folders.zip)

**Comment by texhex** [comment]
@napzero I think that issue is missing some explanation. Is this about adding the 9470m to the out-of-the-box models list?

**Comment by napzero** [comment]
Ah yes, my bad. I'm contributing this, if you wish to include it!

**Comment by thecatdidit** [comment]
@napzero EliteBook 9470m settings worked like a charm. Thanks!

I'll be posting EliteBook 9480m soon, hopefully.

**Comment by thecatdidit** [comment]
@napzero  @texhex HP EliteBook Folio 9480m posted!

**Comment by texhex** [comment]
@napzero Thanks, will check it in a minute.

**Comment by texhex** [comment]
@napzero I checked the files, everything we need is in there, thank you!

Just one question: You have disabled both UEFI and Secure Boot in BIOS-Settings.txt:

```
#Boot Mode==UEFI Native (Without CSM)
#SecureBoot==Enable
```

Does this mean the 9470m does not support these settings or they are supported but you do not use them?

**Comment by napzero** [comment]
Sorry, I didn't test that value, we don't use UEFI yet 😬

**Comment by texhex** [comment]
@napzero No problem, then we'll keep this example as is. Version [3.4.1](https://github.com/texhex/BiosSledgehammer/releases/tag/v3.4.1) includes your changes, thanks for contributing!
