### ISSUE TITLE
HP EliteBook 840 G4 - Updated model with BIOS 1.16, TPM 7.63

### ISSUE THREAD

**Issue by thecatdidit** [texhex/BiosSledgehammer#59]
HP has released **BIOS 1.16** and **TPM 7.63** for the EliteBook 840 G4. I am attaching a complete model folder reflecting these updates and keeping the other files as they are. 

[HP EliteBook 840 G4.zip](https://github.com/texhex/BiosSledgehammer/files/2017403/HP.EliteBook.840.G4.zip)

References

BIOS 1.16 (Softpaq 87115): **(https://ftp.hp.com/pub/softpaq/sp87001-87500/sp87115.html)**
TPM 7.63 (Softpaq 87492): **(https://ftp.hp.com/pub/softpaq/sp87001-87500/sp87492.html)**

**Comment by texhex** [comment]
@thecatdidit Thanks, the release notes look like HP did some serious bug fixing there. 

Please note that in the newest release all EliteBook 8xx G4 series are now using a shared folder, so I have moved the BIOS to \Shared\HP EliteBook 8xx G4. Also, your BIOS-Update.txt was still set to version 1.15.

Regarding the TPM Update, please see the already existing issue #56.

**Comment by texhex** [comment]
File added, closing issue.

**Comment by thecatdidit** [comment]
@texhex Oh! I totally missed that collaboration of the 8xx G4 model series. My mistake :) . Thanks for the insight on that.

**Comment by texhex** [comment]
@thecatdidit No problem, no harm done.
