### ISSUE TITLE
HP EliteBook 9480m - BIOS Update 1.43

### ISSUE THREAD

**Issue by thecatdidit** [texhex/BiosSledgehammer#60]
HP has release **BIOS 1.43** for the EliteBook 9480m.

Attached is a ZIP of the model folder reflecting the newer BIOS version. All other files are unchanged with the current build.

Reference:

* BIOS Update 1.43 (Softpaq 87494): **[https://ftp.hp.com/pub/softpaq/sp87001-87500/sp87494.html](url)

[HP EliteBook Folio 9480m.zip](https://github.com/texhex/BiosSledgehammer/files/2017549/HP.EliteBook.Folio.9480m.zip)

**Comment by texhex** [comment]
@thecatdidit Thanks, added the new download file and changed BIOS-Update.txt to reflect the new version.

**Comment by texhex** [comment]
File added, closing issue.
