### ISSUE TITLE
prodesk 400 g3 shared and elitebook 840 g4 shared

### ISSUE THREAD

**Issue by TimMagellan** [texhex/BiosSledgehammer#66]
Here are the updated URLs for these two items in SPDownload script. The original URLs failed when I ran the script. Once I updated the script with these new URLs everything downloaded properly.

HP ProDesk 4x0 G3 download urls
https://ftp.hp.com/pub/softpaq/sp87501-88000/sp87843.html
https://ftp.hp.com/pub/softpaq/sp87501-88000/sp87843.exe

HP EliteBook 8xx G4 download urls
https://ftp.hp.com/pub/softpaq/sp87501-88000/sp87849.html
https://ftp.hp.com/pub/softpaq/sp87501-88000/sp87849.exe

**Comment by texhex** [comment]
At least some word about what this issue is about would be nice.

**Comment by karlis-vitols** [comment]
If I understand him correctly, then he means the example .exe download script (StartExampleDownloads.bat). Some of the links right now are not working, because they are  pointing to the addresses mentioned above. Obviously, it breaks the download .script, but can be fixed by changing SPDownload.txt files for the affected models.
Do you need a list? 
There are some 4 or 5 models with this problem. What is funny, that ME FW version is not actually changed, its just that SP have different numbers now.

**Comment by datagutten** [comment]
sp87434 is labeled "Intel Corporate Management Engine (ME) Firmware Component - Kaby Lake" with version "11.8.50.3470 REV: A PASS: 2", sp87849 is labeled "Intel Management Engine (ME) Firmware Component" with version "11.8.50.3470 REV: A PASS: 1".
I thought I had submitted this already, but it was only in my working directory and not committed.

**Comment by texhex** [comment]
Sometimes you really wonder if there is somebody at HP Inc. that works in the "How to break things and surprise the customer" department....

@devtestmagdevtest @karlis-vitols Thanks, now I understand. 

@datagutten If you already have the files ready to go, I would appreciate a PR and then merge it.

Regarding the list @karlis-vitols: Thanks, that would be nice but please let's first wait if @datagutten creates a PR that will fix those. If after that still some things are broken, I would be happy for any help on this.

**Comment by texhex** [comment]
@devtestmagdevtest The PR #68 from @datagutten should fix the issues you have found, so I will close this issue. Please feel free to reopen if something is missing.

@karlis-vitols If there are any other broken links, please open a new issue and we'll try to fix them. Thanks.
