### ISSUE TITLE
HP EliteBoolk Folio 9480m - BIOS Update 1.46/ME Update 9.5.65.3000

### ISSUE THREAD

**Issue by thecatdidit** [texhex/BiosSledgehammer#83]
I updated the folder settings before running the Softpaq download to ensure everything downloaded that was desired.

BIOS Update 01.46 was released on 20 Aug 2018
ME Update 9.5.65.3000 was released on 20 Aug 2018 as well

The system is getting long in the tooth, but plenty of them are still out there. Hopefully, this will help!

[HP EliteBook Folio 9480m.zip](https://github.com/texhex/BiosSledgehammer/files/3020662/HP.EliteBook.Folio.9480m.zip)

**Comment by texhex** [comment]
Thanks, added to the repo!
