### ISSUE TITLE
HP EliteBook 9470m - BIOS Update F.72 (ME is still the same)

### ISSUE THREAD

**Issue by thecatdidit** [texhex/BiosSledgehammer#84]
HP release BIOS  Update F.72 for the EliteBook 9470m on 15 August 2018. 

The model isn't getting as much mileage as it used to, but every little bit helps!

[HP EliteBook Folio 9470m.zip](https://github.com/texhex/BiosSledgehammer/files/3020672/HP.EliteBook.Folio.9470m.zip)

**Comment by texhex** [comment]
Thanks, updated!
