### ISSUE TITLE
HP EliteBook 8xx G4 (Shared): BIOS 01.25/ME 11.8.60.3561

### ISSUE THREAD

**Issue by thecatdidit** [texhex/BiosSledgehammer#85]
* BIOS 1.25 (sp94779/2019-02-01)
*ME 11.8.60.3561 (sp93332/2019-01-04)

Attached is modified folder as ZIP
[HP EliteBook 8xx G4.zip](https://github.com/texhex/BiosSledgehammer/files/3020684/HP.EliteBook.8xx.G4.zip)

Thanks!

**Comment by texhex** [comment]
Thanks! 

As information, there was a typo in the SPaqURL for the BIOS: The SP is 94779, not 94770. Not a big deal, but just in case you wonder if you ever need to to download the BIOS.
