### ISSUE TITLE
HP EliteBook 8xx G5 (Shared): BIOS Update 1.06

### ISSUE THREAD

**Issue by thecatdidit** [texhex/BiosSledgehammer#86]
* BIOS Update 1.06 (sp94780/2019-02-01) was released

Attached is an updated framework for the folder.

[HP EliteBook 8xx G5.zip](https://github.com/texhex/BiosSledgehammer/files/3020691/HP.EliteBook.8xx.G5.zip)

Thanks!

**Comment by texhex** [comment]
Thanks, added!
