### ISSUE TITLE
Issues updating HP Elite Compaq 8300 BIOS

### ISSUE THREAD

**Issue by GregoryMachin** [texhex/BiosSledgehammer#92]
Hi,

I'm struggelling to get the BIOS to update on the HP Elite Compaq 8300, HP Elite 800 G1. In both cases the BIOS update utility fails with  "Error Code  0x00000113  INCORRECT_PASSWORD". The BiosSledgehammer script confirms that the password file works, as does manual login, so I'm a bit lost, I haven't found anything useful on google. So I'm hoping I'm not the only one that has experienced this issue and someone can suggest an answer.  
 
Here is the BiosSledgehammer log:

**********************
Windows PowerShell transcript start
Start time: 20191029150156
Username: WAIKATO\adwmaching
RunAs User: WAIKATO\adwmaching
Configuration Name: 
Machine: computername (Microsoft Windows NT 10.0.17763.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File c:\Temp\BiosSledgehammer-Firmware Upgrade 10\BiosSledgehammer.ps1 -WaitAtEnd
Process ID: 1812
PSVersion: 5.1.17763.592
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.592
BuildVersion: 10.0.17763.592
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\WINDOWS\temp\BiosSledgehammer.ps1.log-06.txt

            _
    jgs   ./ |   
         /  /    BIOS Sledgehammer Version 5.2.0
       /'  /     Copyright (c) 2015-2018 Michael 'Tex' Hex
      /   /      
     /    \      https://github.com/texhex/BiosSledgehammer
    |      `\   
    |        |                                ___________________
    |        |___________________...-------'''- - -  =- - =  - = `.
   /|        |                   \-  =  = -  -= - =  - =-   =  - =|
  ( |        |                    |= -= - = - = - = - =--= = - = =|
   \|        |___________________/- = - -= =_- =_-=_- -=_=-=_=_= -|
    |        |                   ```-------...___________________.'
    |________|   
      \    /     This is *NOT* sponsored/endorsed by HP or Intel.  
      |    |     This is *NOT* an official HP or Intel tool.
    ,-'    `-,   
    |        |   Use at your own risk.
    `--------'

 ####################################################################
 ##  THIS SCRIPT MIGHT ALTER YOUR FIRMWARE AND/OR BIOS SETTINGS    ##
 ##                                                                ##
 ##  You have 15 seconds to press CTRL+C to stop it.               ##
 ####################################################################

Verifying environment...
  Success
Verifying BIOS Configuration Utility (BCU) can communicate with BIOS.
  Trying to read Universally Unique Identifier (UUID)...
  Success
Collecting system information...

  Name.........: computername
  Model........: HP Compaq Elite 8300 USDT
  SKU..........: QV997AV
  BIOS (Raw)...: K01 v02.05
  BIOS Family..: K01
  BIOS Version.: v02.05  (Numerical: 2.0.5)
  TPM Vendor...: 1229346816
  TPM Firmware.: 3.17  (Numerical: 3.17)
  TPM Spec.....: 1.2  (Numerical: 1.2)

***** Locate Model Folder ***************************************
Searching [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\Models]
  for SKU [QV997AV] or [HP Compaq Elite 8300 USDT]...
  Searching for SKU folder...
    No folder found
  Searching for exactly matching folder for this model...
    No folder found
  Searching for partially matching folder...
    Matching folder: [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\Models\HP Compaq Elite 8300]
Model folder is [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\Models\HP Compaq Elite 8300]
Section -Model Folder- finished
*****************************************************************

***** Determine BIOS Password ***********************************
Checking which asset value setting name this device supports...
  Testing setting name [Asset Tracking Number]...
  Setting is supported, will use it for write tests
Testing BIOS password files from [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\PwdFiles]...
Original asset value: [computername]
Asset value used for testing: [21qms6pnhvxadk]
Trying to write asset value using password file []...
Trying to write asset value using password file [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\PwdFiles\biospassword.bin]...
Success; password file is [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\PwdFiles\biospassword.bin]!
Restoring original asset value
Section -Determine BIOS Password- finished
*****************************************************************

***** BIOS Update ***********************************************
Reading settings from [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\Models\HP Compaq Elite 8300\BIOS-Update.txt]...
Not found, looking for shared file [Shared-BIOS-Update.txt] in same directory...
  Shared file found
Using settings from [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\Shared\HP Compaq Elite 8300\BIOS-Update.txt]
Current BIOS Version: v02.05  (Numerical: 2.0.5)
Desired BIOS Version: 03.08  (Numerical: 3.0.8)
BIOS update required!
***** BIOS settings for BIOS update *****************************
Reading settings from [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\Models\HP Compaq Elite 8300\BIOS-Update-Settings.txt]...
Not found, looking for shared file [Shared-BIOS-Update-Settings.txt] in same directory...
No settings file was found
Section -BIOS settings for BIOS update- finished
*****************************************************************
BIOS family is [K01]
Checking if the computer is on AC or DC (battery) power...
Querying CIM for Win32_Battery.BatteryStatus failed (The property 'BatteryStatus' cannot be found on this object. Verify that the property exists.), assuming this computer has no battery.
  Battery status is OK or no battery present.
::: Preparing launch of update executable :::
Copying [C:\Temp\BiosSledgehammer-Firmware Upgrade 10\Shared\HP Compaq Elite 8300\BIOS-03.08\]
     to [C:\Users\adwmaching\AppData\Local\Temp\BIOS-03.08\] ...
Done
Deleting [*.log] in target folder
Starting:
  C:\Users\adwmaching\AppData\Local\Temp\BIOS-03.08\HPQFlash\hpqFlash.exe
  -s -p"C:\Users\adwmaching\AppData\Local\Temp\biospassword.bin"
  Done, return code is 259
--- Output ---
--------------
  Waiting 10 seconds before checking if the process is still running...
   [hpqFlash] is no longer running, waiting 5 seconds to allow cleanup...
  Start of [C:\Users\adwmaching\AppData\Local\Temp\BIOS-03.08\HPQFlash\hpqFlash.exe] done
Checking for first file matching [*.log] in [C:\Users\adwmaching\AppData\Local\Temp\BIOS-03.08]...
***** ::BEGIN:: C:\Users\adwmaching\AppData\Local\Temp\BIOS-03.08\HPQFlash\hpqFlash.log *****
2019/10/29 15:02:32.588|00001F8C|Information|ChpqFlashApp::InitInstance|
2019/10/29 15:02:32.590|00001F8C|Information|ChpqFlashApp::InitInstance|--- START NEW HPQFLASH SESSION, HPQFLASH version 4.50.1.1 ---
2019/10/29 15:02:32.591|00001F8C|Information|ChpqFlashApp::CPQFProcessCmdLineArgs|Command line = -s -p"C:\Users\adwmaching\AppData\Local\Temp\biospassword.bin"
2019/10/29 15:02:35.803|00001F8C|Information|CCpqCIMIntf::GetsystemInfo|System name = HP COMPAQ ELITE 8300 USDT
2019/10/29 15:02:35.806|00001F8C|Information|CCpqCIMIntf::GetsystemInfo|System ID = 0x3398
2019/10/29 15:02:35.807|00001F8C|Information|CCpqCIMIntf::GetsystemInfo|System Serial Number = AUD31605QH
2019/10/29 15:02:35.809|00001F8C|Information|CCpqCIMIntf::GetsystemInfo|AT-p supported = 0 (0:  not supported, 1 supported)
2019/10/29 15:02:35.810|00001F8C|Information|CCpqCIMIntf::GetsystemInfo|Version of BIOS in system:
2019/10/29 15:02:35.812|00001F8C|Information|CCpqCIMIntf::GetsystemInfo|   Family = K01
2019/10/29 15:02:35.813|00001F8C|Information|CCpqCIMIntf::GetsystemInfo|   Major version = 0x2, Minor Version = 0x05
2019/10/29 15:02:35.814|00001F8C|Information|CCpqCIMIntf::GetsystemInfo|   Release Date = 05/07/2012
2019/10/29 15:02:35.834|00001F8C|Information|ChpqFlashApp::hpqFlashInSilentMode|Flashing in silent mode
2019/10/29 15:02:36.164|00001F8C|Information|CPQMessageBox|Error Code  0x00000113  INCORRECT_PASSWORD

2019/10/29 15:02:36.164|00001F8C|Information|ChpqFlashApp::hpqFlashInSilentMode|Exit hpqFlashInSilentMode, bStatus = 0
2019/10/29 15:02:36.164|00001F8C|Information|ChpqFlashApp::ExitInstance|Exit hpqFlash:  Return Code = 0x103
2019/10/29 15:02:36.164|00001F8C|Information|ChpqFlashApp::ExitInstance|--- END HPQFLASH SESSION ---
***** ::END:: C:\Users\adwmaching\AppData\Local\Temp\BIOS-03.08\HPQFlash\hpqFlash.log *****
::: Launching update executable finished :::
PS>TerminatingError(): "BIOS update failed, update program returned code 259"
C:\Temp\BiosSledgehammer-Firmware Upgrade 10\BiosSledgehammer.ps1 : BIOS update failed, update program returned code 259
At C:\Temp\BiosSledgehammer-Firmware Upgrade 10\BiosSledgehammer.ps1:1623 char:29
+ ...             throw "BIOS update failed, update program returned code $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at Update-BiosFirmware, C:\Temp\BiosSledgehammer-Firmware Upgrade 10\BiosSledgehammer.ps1: line 1623
at <ScriptBlock>, C:\Temp\BiosSledgehammer-Firmware Upgrade 10\BiosSledgehammer.ps1: line 3021
    + CategoryInfo          : OperationStopped: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,BiosSledgehammer.ps1
C:\Temp\BiosSledgehammer-Firmware Upgrade 10\BiosSledgehammer.ps1 : BIOS update failed, update program returned code
259
At C:\Temp\BiosSledgehammer-Firmware Upgrade 10\BiosSledgehammer.ps1:1623 char:29
+ ...             throw "BIOS update failed, update program returned code $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at Update-BiosFirmware, C:\Temp\BiosSledgehammer-Firmware Upgrade 10\BiosSledgehammer.ps1: line 1623
at <ScriptBlock>, C:\Temp\BiosSledgehammer-Firmware Upgrade 10\BiosSledgehammer.ps1: line 3021
    + CategoryInfo          : OperationStopped: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,BiosSledgehammer.ps1

BIOS Sledgehammer finished, return code 666.
Thank you, please come again!
Waiting 30 seconds...
**********************
Windows PowerShell transcript end
End time: 20191029150321
**********************

Thank you.
G

**Comment by texhex** [comment]
This is indeed very strange, given that the BIOS value change with the exact same password worked. 

I think the message does not mean "Password incorrect" but instead "Incorrect update path". For the Elite 8300, we seem to have the same topic as with the Pro 8300: it requires a [Two Step BIOS Update](https://github.com/texhex/BiosSledgehammer#two-step-bios-update-process) to move to 3.x.

Please first try flashing [v2.99](https://ftp.hp.com/pub/softpaq/sp73001-73500/sp73099.exe) (you can see this release by clicking "Previous releases" for BIOS v03.08), then update to 3.08.

**Comment by GregoryMachin** [comment]
Great thanks. 
I'll give it a go. 

Awesome script thanks for all your work.

**Comment by texhex** [comment]
@GregoryMachin As there was no update on this issue, I'm assuming this is solved with the extra BIOS update for the transition BIOS. I'm closing this issue.
