### ISSUE TITLE
HP ZBook 14 G2 Model Not Listed  - Can't Update TPM from 1.2 to 2.0

### ISSUE THREAD

**Issue by NormanFPC** [texhex/BiosSledgehammer#97]
I have a 2015 HP ZBook 14 G2 and the model isn't listed in your models folder.

I would like to upgrade the TPM from 1.2 to 2.0. Its an Infineon chip.

If it matters, the BIOS has already been upgraded for the M71 family from 2015 to the most current version in 2020.

Your script would allow me to set TPM to 2.0. A pity I can't run it on my mobile workstation.

I would much appreciate your assistance in addressing this issue.

**Comment by texhex** [comment]
Sorry, but can't help you there. This project is a wrapper around the updates that HP delivers. So if HP does not have an update for that device, it can't be upgrade.
